version: '3'

services:
  armsim:
    container_name: arm_sim
    image: arm_sim:latest
    network_mode: host
    ipc: host
    environment:
      - DISPLAY
    volumes:
      - /tmp.X11-unix:/tmp.X11-unix
    restart: always
    stdin_open: true
    tty: true