sensors:
  - kinect_pointcloud
kinect_pointcloud:
  filtered_cloud_topic: filtered_cloud
  max_range: 5.0
  max_update_rate: 1.0
  padding_offset: 0.05
  padding_scale: 1.2
  point_cloud_topic: /wrist_rgbd_depth_sensor/points
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater